name: Deploy Code to Server  # Name of your workflow

on:
  push:
    branches:
      - main  # This workflow runs on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The environment the action will run in

    steps:
    - name: Checkout Repository  # Step to check out your repository
      uses: actions/checkout@v2

    - name: Deploy via SSH  # Step to SSH into your server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}  # Server IP from GitHub Secrets
        username: ${{ secrets.SERVER_USER }}  # Servecrets
        key: ${{ secrets.SERVER_SSH_KEY }}  # SSH Private key from Secrets
        script: |
          cd Server-Administration
          ./update.sh  # The deployment script that runs on the server
